import type { QueryInterface } from "sequelize";

const ownedTables = [
    "carts",
    "cart_items",
    "orders",
    "order_items",
    "order_status_history",
    "vouchers",
    "voucher_branches",
    "voucher_redemptions",
    "payment_methods",
    "payments",
    "payment_events",
] as const;

const createStatements = [
    `CREATE TABLE \`carts\` (
        \`id\` BIGINT NOT NULL AUTO_INCREMENT,
        \`customer_id\` BIGINT NOT NULL,
        \`created_at\` TIMESTAMP NOT NULL,
        \`updated_at\` TIMESTAMP NOT NULL,
        PRIMARY KEY (\`id\`),
        UNIQUE KEY \`uq_carts_customer\` (\`customer_id\`),
        CONSTRAINT \`fk_carts_customer\` FOREIGN KEY (\`customer_id\`) REFERENCES \`customers\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE \`cart_items\` (
        \`id\` BIGINT NOT NULL AUTO_INCREMENT,
        \`cart_id\` BIGINT NOT NULL,
        \`product_variant_id\` BIGINT NOT NULL,
        \`quantity\` INT NOT NULL,
        \`created_at\` TIMESTAMP NOT NULL,
        \`updated_at\` TIMESTAMP NOT NULL,
        PRIMARY KEY (\`id\`),
        CONSTRAINT \`uq_cart_items_cart_variant\` UNIQUE (\`cart_id\`, \`product_variant_id\`),
        KEY \`idx_cart_items_variant\` (\`product_variant_id\`),
        CONSTRAINT \`chk_cart_items_quantity\` CHECK (\`quantity\` > 0),
        CONSTRAINT \`fk_cart_items_cart\` FOREIGN KEY (\`cart_id\`) REFERENCES \`carts\` (\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT,
        CONSTRAINT \`fk_cart_items_variant\` FOREIGN KEY (\`product_variant_id\`) REFERENCES \`product_variants\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE \`orders\` (
        \`id\` BIGINT NOT NULL AUTO_INCREMENT,
        \`code\` VARCHAR(50) NOT NULL,
        \`checkout_key\` VARCHAR(191) NOT NULL,
        \`customer_id\` BIGINT NULL,
        \`fulfillment_branch_id\` BIGINT NOT NULL,
        \`created_by_account_id\` BIGINT NULL,
        \`channel\` ENUM('online', 'in_store') NOT NULL,
        \`fulfillment_type\` ENUM('delivery', 'store_pickup', 'carry_out') NOT NULL,
        \`fulfillment_status\` ENUM('unfulfilled', 'preparing', 'ready_for_pickup', 'shipping', 'fulfilled', 'exception', 'cancelled') NOT NULL DEFAULT 'unfulfilled',
        \`status\` ENUM('pending', 'confirmed', 'completed', 'cancelled') NOT NULL DEFAULT 'pending',
        \`currency\` CHAR(3) NOT NULL DEFAULT 'VND',
        \`subtotal_amount\` DECIMAL(19,4) NOT NULL,
        \`discount_amount\` DECIMAL(19,4) NOT NULL DEFAULT 0,
        \`shipping_fee\` DECIMAL(19,4) NOT NULL DEFAULT 0,
        \`total_amount\` DECIMAL(19,4) NOT NULL,
        \`customer_name\` VARCHAR(255) NULL,
        \`customer_email\` VARCHAR(255) NULL,
        \`customer_phone\` VARCHAR(30) NULL,
        \`customer_message\` VARCHAR(1000) NULL,
        \`cancelled_at\` TIMESTAMP NULL,
        \`cancelled_by_account_id\` BIGINT NULL,
        \`cancellation_reason\` VARCHAR(500) NULL,
        \`fulfilled_at\` TIMESTAMP NULL,
        \`placed_at\` TIMESTAMP NOT NULL,
        \`created_at\` TIMESTAMP NOT NULL,
        \`updated_at\` TIMESTAMP NOT NULL,
        PRIMARY KEY (\`id\`),
        UNIQUE KEY \`uq_orders_code\` (\`code\`),
        UNIQUE KEY \`uq_orders_checkout_key\` (\`checkout_key\`),
        KEY \`idx_orders_customer_created\` (\`customer_id\`, \`created_at\`),
        KEY \`idx_orders_branch_status_created\` (\`fulfillment_branch_id\`, \`status\`, \`created_at\`),
        KEY \`idx_orders_status_created\` (\`status\`, \`created_at\`),
        KEY \`idx_orders_created_by\` (\`created_by_account_id\`),
        KEY \`idx_orders_cancelled_by\` (\`cancelled_by_account_id\`),
        CONSTRAINT \`chk_orders_currency\` CHECK (\`currency\` = 'VND'),
        CONSTRAINT \`chk_order_amounts\` CHECK (\`subtotal_amount\` >= 0 AND \`discount_amount\` >= 0 AND \`discount_amount\` <= \`subtotal_amount\` AND \`shipping_fee\` >= 0 AND \`total_amount\` = \`subtotal_amount\` - \`discount_amount\` + \`shipping_fee\`),
        CONSTRAINT \`chk_online_customer\` CHECK (\`channel\` <> 'online' OR \`customer_id\` IS NOT NULL),
        CONSTRAINT \`chk_pos_actor\` CHECK (\`channel\` <> 'in_store' OR \`created_by_account_id\` IS NOT NULL),
        CONSTRAINT \`chk_carry_out_channel\` CHECK (\`fulfillment_type\` <> 'carry_out' OR \`channel\` = 'in_store'),
        CONSTRAINT \`chk_nondelivery_fee\` CHECK (\`fulfillment_type\` = 'delivery' OR \`shipping_fee\` = 0),
        CONSTRAINT \`chk_completed_fulfilled\` CHECK (\`status\` <> 'completed' OR \`fulfillment_status\` = 'fulfilled'),
        CONSTRAINT \`fk_orders_customer\` FOREIGN KEY (\`customer_id\`) REFERENCES \`customers\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_orders_branch\` FOREIGN KEY (\`fulfillment_branch_id\`) REFERENCES \`branches\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_orders_created_by\` FOREIGN KEY (\`created_by_account_id\`) REFERENCES \`accounts\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_orders_cancelled_by\` FOREIGN KEY (\`cancelled_by_account_id\`) REFERENCES \`accounts\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE \`order_items\` (
        \`id\` BIGINT NOT NULL AUTO_INCREMENT,
        \`order_id\` BIGINT NOT NULL,
        \`product_id\` BIGINT NULL,
        \`product_variant_id\` BIGINT NULL,
        \`sku_snapshot\` VARCHAR(100) NOT NULL,
        \`product_name_snapshot\` VARCHAR(255) NOT NULL,
        \`size_name_snapshot\` VARCHAR(100) NOT NULL,
        \`image_snapshot\` JSON NULL,
        \`unit_price\` DECIMAL(19,4) NOT NULL,
        \`discount_amount\` DECIMAL(19,4) NOT NULL DEFAULT 0,
        \`quantity\` INT NOT NULL,
        \`line_total\` DECIMAL(19,4) NOT NULL,
        \`created_at\` TIMESTAMP NOT NULL,
        PRIMARY KEY (\`id\`),
        KEY \`idx_order_items_order\` (\`order_id\`),
        KEY \`idx_order_items_product\` (\`product_id\`),
        KEY \`idx_order_items_variant\` (\`product_variant_id\`),
        CONSTRAINT \`chk_order_items_quantity\` CHECK (\`quantity\` > 0),
        CONSTRAINT \`chk_order_item_amounts\` CHECK (\`unit_price\` >= 0 AND \`discount_amount\` >= 0 AND \`discount_amount\` <= \`unit_price\` * \`quantity\` AND \`line_total\` = \`unit_price\` * \`quantity\` - \`discount_amount\`),
        CONSTRAINT \`fk_order_items_order\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_order_items_product\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_order_items_variant\` FOREIGN KEY (\`product_variant_id\`) REFERENCES \`product_variants\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE \`order_status_history\` (
        \`id\` BIGINT NOT NULL AUTO_INCREMENT,
        \`order_id\` BIGINT NOT NULL,
        \`from_status\` ENUM('pending', 'confirmed', 'completed', 'cancelled') NULL,
        \`to_status\` ENUM('pending', 'confirmed', 'completed', 'cancelled') NOT NULL,
        \`from_fulfillment_status\` ENUM('unfulfilled', 'preparing', 'ready_for_pickup', 'shipping', 'fulfilled', 'exception', 'cancelled') NULL,
        \`to_fulfillment_status\` ENUM('unfulfilled', 'preparing', 'ready_for_pickup', 'shipping', 'fulfilled', 'exception', 'cancelled') NOT NULL,
        \`changed_by_account_id\` BIGINT NULL,
        \`note\` VARCHAR(500) NULL,
        \`changed_at\` TIMESTAMP NOT NULL,
        PRIMARY KEY (\`id\`),
        KEY \`idx_order_status_history_order_changed\` (\`order_id\`, \`changed_at\`),
        KEY \`idx_order_status_history_actor\` (\`changed_by_account_id\`),
        CONSTRAINT \`fk_order_status_history_order\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_order_status_history_actor\` FOREIGN KEY (\`changed_by_account_id\`) REFERENCES \`accounts\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE \`vouchers\` (
        \`id\` BIGINT NOT NULL AUTO_INCREMENT,
        \`code\` VARCHAR(50) NOT NULL,
        \`description\` VARCHAR(500) NULL,
        \`discount_type\` ENUM('percent', 'fixed') NOT NULL,
        \`discount_value\` DECIMAL(19,4) NOT NULL,
        \`min_order_amount\` DECIMAL(19,4) NOT NULL DEFAULT 0,
        \`max_discount_amount\` DECIMAL(19,4) NULL,
        \`usage_limit\` INT NULL,
        \`per_customer_limit\` INT NULL,
        \`applies_to_channel\` ENUM('all', 'online', 'in_store') NOT NULL DEFAULT 'all',
        \`branch_scope\` ENUM('all', 'selected') NOT NULL DEFAULT 'all',
        \`starts_at\` TIMESTAMP NOT NULL,
        \`ends_at\` TIMESTAMP NOT NULL,
        \`status\` ENUM('draft', 'active', 'inactive', 'expired') NOT NULL DEFAULT 'draft',
        \`created_at\` TIMESTAMP NOT NULL,
        \`updated_at\` TIMESTAMP NOT NULL,
        PRIMARY KEY (\`id\`),
        UNIQUE KEY \`uq_vouchers_code\` (\`code\`),
        CONSTRAINT \`chk_voucher_amounts\` CHECK (\`discount_value\` > 0 AND \`min_order_amount\` >= 0 AND (\`max_discount_amount\` IS NULL OR \`max_discount_amount\` >= 0)),
        CONSTRAINT \`chk_voucher_percent\` CHECK (\`discount_type\` <> 'percent' OR \`discount_value\` <= 100),
        CONSTRAINT \`chk_voucher_dates\` CHECK (\`ends_at\` > \`starts_at\`),
        CONSTRAINT \`chk_voucher_limits\` CHECK ((\`usage_limit\` IS NULL OR \`usage_limit\` > 0) AND (\`per_customer_limit\` IS NULL OR \`per_customer_limit\` > 0))
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE \`voucher_branches\` (
        \`voucher_id\` BIGINT NOT NULL,
        \`branch_id\` BIGINT NOT NULL,
        PRIMARY KEY (\`voucher_id\`, \`branch_id\`),
        KEY \`idx_voucher_branches_branch\` (\`branch_id\`),
        CONSTRAINT \`fk_voucher_branches_voucher\` FOREIGN KEY (\`voucher_id\`) REFERENCES \`vouchers\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_voucher_branches_branch\` FOREIGN KEY (\`branch_id\`) REFERENCES \`branches\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE \`voucher_redemptions\` (
        \`id\` BIGINT NOT NULL AUTO_INCREMENT,
        \`voucher_id\` BIGINT NOT NULL,
        \`order_id\` BIGINT NOT NULL,
        \`customer_id\` BIGINT NULL,
        \`voucher_code_snapshot\` VARCHAR(50) NOT NULL,
        \`discount_amount\` DECIMAL(19,4) NOT NULL,
        \`status\` ENUM('reserved', 'redeemed', 'released') NOT NULL DEFAULT 'reserved',
        \`reserved_at\` TIMESTAMP NOT NULL,
        \`redeemed_at\` TIMESTAMP NULL,
        \`released_at\` TIMESTAMP NULL,
        PRIMARY KEY (\`id\`),
        UNIQUE KEY \`uq_voucher_redemptions_order\` (\`order_id\`),
        KEY \`idx_voucher_redemptions_voucher_status\` (\`voucher_id\`, \`status\`),
        KEY \`idx_voucher_redemptions_customer_voucher\` (\`customer_id\`, \`voucher_id\`),
        CONSTRAINT \`chk_voucher_redemptions_discount\` CHECK (\`discount_amount\` >= 0),
        CONSTRAINT \`fk_voucher_redemptions_voucher\` FOREIGN KEY (\`voucher_id\`) REFERENCES \`vouchers\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_voucher_redemptions_order\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_voucher_redemptions_customer\` FOREIGN KEY (\`customer_id\`) REFERENCES \`customers\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE \`payment_methods\` (
        \`id\` BIGINT NOT NULL AUTO_INCREMENT,
        \`code\` VARCHAR(50) NOT NULL,
        \`name\` VARCHAR(150) NOT NULL,
        \`description\` VARCHAR(500) NULL,
        \`is_active\` BOOLEAN NOT NULL DEFAULT TRUE,
        \`created_at\` TIMESTAMP NOT NULL,
        \`updated_at\` TIMESTAMP NOT NULL,
        PRIMARY KEY (\`id\`),
        UNIQUE KEY \`uq_payment_methods_code\` (\`code\`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE \`payments\` (
        \`id\` BIGINT NOT NULL AUTO_INCREMENT,
        \`order_id\` BIGINT NOT NULL,
        \`payment_method_id\` BIGINT NOT NULL,
        \`collected_by_account_id\` BIGINT NULL,
        \`provider\` VARCHAR(50) NOT NULL,
        \`merchant_reference\` VARCHAR(191) NOT NULL,
        \`provider_transaction_id\` VARCHAR(191) NULL,
        \`amount\` DECIMAL(19,4) NOT NULL,
        \`status\` ENUM('pending', 'processing', 'completed', 'failed', 'cancelled') NOT NULL DEFAULT 'pending',
        \`paid_at\` TIMESTAMP NULL,
        \`created_at\` TIMESTAMP NOT NULL,
        \`updated_at\` TIMESTAMP NOT NULL,
        PRIMARY KEY (\`id\`),
        UNIQUE KEY \`uq_payments_merchant_reference\` (\`merchant_reference\`),
        CONSTRAINT \`uq_payment_provider_transaction\` UNIQUE (\`provider\`, \`provider_transaction_id\`),
        KEY \`idx_payments_order_created\` (\`order_id\`, \`created_at\`),
        KEY \`idx_payments_method\` (\`payment_method_id\`),
        KEY \`idx_payments_collector\` (\`collected_by_account_id\`),
        KEY \`idx_payments_status_created\` (\`status\`, \`created_at\`),
        CONSTRAINT \`chk_payments_amount\` CHECK (\`amount\` > 0),
        CONSTRAINT \`chk_payment_completion_time\` CHECK (\`status\` <> 'completed' OR \`paid_at\` IS NOT NULL),
        CONSTRAINT \`fk_payments_order\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_payments_method\` FOREIGN KEY (\`payment_method_id\`) REFERENCES \`payment_methods\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_payments_collector\` FOREIGN KEY (\`collected_by_account_id\`) REFERENCES \`accounts\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE \`payment_events\` (
        \`id\` BIGINT NOT NULL AUTO_INCREMENT,
        \`payment_id\` BIGINT NOT NULL,
        \`provider\` VARCHAR(50) NOT NULL,
        \`event_key\` VARCHAR(191) NOT NULL,
        \`event_type\` VARCHAR(100) NOT NULL,
        \`verified_at\` TIMESTAMP NOT NULL,
        \`processed_at\` TIMESTAMP NULL,
        \`created_at\` TIMESTAMP NOT NULL,
        PRIMARY KEY (\`id\`),
        CONSTRAINT \`uq_payment_event_provider_key\` UNIQUE (\`provider\`, \`event_key\`),
        KEY \`idx_payment_events_payment_created\` (\`payment_id\`, \`created_at\`),
        CONSTRAINT \`fk_payment_events_payment\` FOREIGN KEY (\`payment_id\`) REFERENCES \`payments\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `ALTER TABLE \`reviews\` ADD CONSTRAINT \`fk_reviews_order_item\` FOREIGN KEY (\`order_item_id\`) REFERENCES \`order_items\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`,
];

const migration = {
    up: async (queryInterface: QueryInterface): Promise<void> => {
        const existingTables = new Set(
            (await queryInterface.showAllTables()).map((tableName) => tableName.toLowerCase()),
        );
        const overlappingTables = ownedTables.filter((tableName) => existingTables.has(tableName));

        if (overlappingTables.length > 0) {
            throw new Error(
                `Database V2 commerce baseline refuses to run when any owned table already exists: ${overlappingTables.join(", ")}.`,
            );
        }

        for (const statement of createStatements) {
            await queryInterface.sequelize.query(statement);
        }
    },
};

export default migration;
