import type { QueryInterface } from "sequelize";

const ownedTables = [
    "inventories",
    "stock_requests",
    "stock_request_items",
    "stock_request_history",
    "transfer_receipts",
    "transfer_receipt_items",
    "transfer_history",
    "inventory_reservations",
    "inventory_movements",
] as const;

const createStatements = [
    `CREATE TABLE \`inventories\` (
        \`id\` BIGINT NOT NULL AUTO_INCREMENT,
        \`branch_id\` BIGINT NOT NULL,
        \`product_variant_id\` BIGINT NOT NULL,
        \`stock\` INTEGER NOT NULL DEFAULT 0,
        \`created_at\` TIMESTAMP NOT NULL,
        \`updated_at\` TIMESTAMP NOT NULL,
        PRIMARY KEY (\`id\`),
        CONSTRAINT \`uq_inventories_branch_variant\` UNIQUE (\`branch_id\`, \`product_variant_id\`),
        KEY \`idx_inventories_variant\` (\`product_variant_id\`),
        CONSTRAINT \`chk_inventories_stock\` CHECK (\`stock\` >= 0),
        CONSTRAINT \`fk_inventories_branch\` FOREIGN KEY (\`branch_id\`) REFERENCES \`branches\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_inventories_variant\` FOREIGN KEY (\`product_variant_id\`) REFERENCES \`product_variants\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE \`stock_requests\` (
        \`id\` BIGINT NOT NULL AUTO_INCREMENT,
        \`code\` VARCHAR(50) NOT NULL,
        \`from_branch_id\` BIGINT NOT NULL,
        \`to_branch_id\` BIGINT NOT NULL,
        \`status\` ENUM('pending', 'approved', 'rejected', 'cancelled', 'fulfilled') NOT NULL DEFAULT 'pending',
        \`created_by_account_id\` BIGINT NOT NULL,
        \`approved_by_account_id\` BIGINT NULL,
        \`approved_at\` TIMESTAMP NULL,
        \`created_at\` TIMESTAMP NOT NULL,
        \`updated_at\` TIMESTAMP NOT NULL,
        PRIMARY KEY (\`id\`),
        UNIQUE KEY \`uq_stock_requests_code\` (\`code\`),
        KEY \`idx_stock_requests_from_branch\` (\`from_branch_id\`),
        KEY \`idx_stock_requests_to_branch\` (\`to_branch_id\`),
        KEY \`idx_stock_requests_created_by\` (\`created_by_account_id\`),
        KEY \`idx_stock_requests_approved_by\` (\`approved_by_account_id\`),
        CONSTRAINT \`chk_stock_request_branches\` CHECK (\`from_branch_id\` <> \`to_branch_id\`),
        CONSTRAINT \`fk_stock_requests_from_branch\` FOREIGN KEY (\`from_branch_id\`) REFERENCES \`branches\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_stock_requests_to_branch\` FOREIGN KEY (\`to_branch_id\`) REFERENCES \`branches\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_stock_requests_created_by\` FOREIGN KEY (\`created_by_account_id\`) REFERENCES \`accounts\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_stock_requests_approved_by\` FOREIGN KEY (\`approved_by_account_id\`) REFERENCES \`accounts\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE \`stock_request_items\` (
        \`id\` BIGINT NOT NULL AUTO_INCREMENT,
        \`stock_request_id\` BIGINT NOT NULL,
        \`product_variant_id\` BIGINT NOT NULL,
        \`quantity\` INTEGER NOT NULL,
        \`note\` VARCHAR(500) NULL,
        \`created_at\` TIMESTAMP NOT NULL,
        \`updated_at\` TIMESTAMP NOT NULL,
        PRIMARY KEY (\`id\`),
        CONSTRAINT \`uq_stock_request_items_request_variant\` UNIQUE (\`stock_request_id\`, \`product_variant_id\`),
        KEY \`idx_stock_request_items_variant\` (\`product_variant_id\`),
        CONSTRAINT \`chk_stock_request_items_quantity\` CHECK (\`quantity\` > 0),
        CONSTRAINT \`fk_stock_request_items_request\` FOREIGN KEY (\`stock_request_id\`) REFERENCES \`stock_requests\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_stock_request_items_variant\` FOREIGN KEY (\`product_variant_id\`) REFERENCES \`product_variants\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE \`stock_request_history\` (
        \`id\` BIGINT NOT NULL AUTO_INCREMENT,
        \`stock_request_id\` BIGINT NOT NULL,
        \`action\` VARCHAR(100) NOT NULL,
        \`performed_by_account_id\` BIGINT NOT NULL,
        \`note\` VARCHAR(500) NULL,
        \`created_at\` TIMESTAMP NOT NULL,
        PRIMARY KEY (\`id\`),
        KEY \`idx_stock_request_history_request_created\` (\`stock_request_id\`, \`created_at\`),
        KEY \`idx_stock_request_history_actor\` (\`performed_by_account_id\`),
        CONSTRAINT \`fk_stock_request_history_request\` FOREIGN KEY (\`stock_request_id\`) REFERENCES \`stock_requests\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_stock_request_history_actor\` FOREIGN KEY (\`performed_by_account_id\`) REFERENCES \`accounts\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE \`transfer_receipts\` (
        \`id\` BIGINT NOT NULL AUTO_INCREMENT,
        \`stock_request_id\` BIGINT NULL,
        \`code\` VARCHAR(50) NOT NULL,
        \`from_branch_id\` BIGINT NOT NULL,
        \`to_branch_id\` BIGINT NOT NULL,
        \`status\` ENUM('pending', 'approved', 'in_transit', 'completed', 'rejected', 'cancelled') NOT NULL DEFAULT 'pending',
        \`created_by_account_id\` BIGINT NOT NULL,
        \`approved_by_account_id\` BIGINT NULL,
        \`approved_at\` TIMESTAMP NULL,
        \`dispatched_at\` TIMESTAMP NULL,
        \`completed_at\` TIMESTAMP NULL,
        \`created_at\` TIMESTAMP NOT NULL,
        \`updated_at\` TIMESTAMP NOT NULL,
        PRIMARY KEY (\`id\`),
        UNIQUE KEY \`uq_transfer_receipts_code\` (\`code\`),
        KEY \`idx_transfer_receipts_stock_request\` (\`stock_request_id\`),
        KEY \`idx_transfer_receipts_route_status\` (\`from_branch_id\`, \`to_branch_id\`, \`status\`),
        KEY \`idx_transfer_receipts_to_branch\` (\`to_branch_id\`),
        KEY \`idx_transfer_receipts_created_by\` (\`created_by_account_id\`),
        KEY \`idx_transfer_receipts_approved_by\` (\`approved_by_account_id\`),
        CONSTRAINT \`chk_transfer_branches\` CHECK (\`from_branch_id\` <> \`to_branch_id\`),
        CONSTRAINT \`fk_transfer_receipts_request\` FOREIGN KEY (\`stock_request_id\`) REFERENCES \`stock_requests\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_transfer_receipts_from_branch\` FOREIGN KEY (\`from_branch_id\`) REFERENCES \`branches\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_transfer_receipts_to_branch\` FOREIGN KEY (\`to_branch_id\`) REFERENCES \`branches\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_transfer_receipts_created_by\` FOREIGN KEY (\`created_by_account_id\`) REFERENCES \`accounts\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_transfer_receipts_approved_by\` FOREIGN KEY (\`approved_by_account_id\`) REFERENCES \`accounts\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE \`transfer_receipt_items\` (
        \`id\` BIGINT NOT NULL AUTO_INCREMENT,
        \`transfer_receipt_id\` BIGINT NOT NULL,
        \`product_variant_id\` BIGINT NOT NULL,
        \`quantity\` INTEGER NOT NULL,
        \`received_quantity\` INTEGER NOT NULL DEFAULT 0,
        \`lost_quantity\` INTEGER NOT NULL DEFAULT 0,
        \`non_sellable_quantity\` INTEGER NOT NULL DEFAULT 0,
        \`note\` VARCHAR(500) NULL,
        \`created_at\` TIMESTAMP NOT NULL,
        \`updated_at\` TIMESTAMP NOT NULL,
        PRIMARY KEY (\`id\`),
        CONSTRAINT \`uq_transfer_receipt_items_receipt_variant\` UNIQUE (\`transfer_receipt_id\`, \`product_variant_id\`),
        KEY \`idx_transfer_receipt_items_variant\` (\`product_variant_id\`),
        CONSTRAINT \`chk_transfer_quantities\` CHECK (\`quantity\` > 0 AND \`received_quantity\` >= 0 AND \`lost_quantity\` >= 0 AND \`non_sellable_quantity\` >= 0 AND \`received_quantity\` + \`lost_quantity\` + \`non_sellable_quantity\` <= \`quantity\`),
        CONSTRAINT \`fk_transfer_receipt_items_receipt\` FOREIGN KEY (\`transfer_receipt_id\`) REFERENCES \`transfer_receipts\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_transfer_receipt_items_variant\` FOREIGN KEY (\`product_variant_id\`) REFERENCES \`product_variants\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE \`transfer_history\` (
        \`id\` BIGINT NOT NULL AUTO_INCREMENT,
        \`transfer_receipt_id\` BIGINT NOT NULL,
        \`action\` VARCHAR(100) NOT NULL,
        \`performed_by_account_id\` BIGINT NOT NULL,
        \`note\` VARCHAR(500) NULL,
        \`created_at\` TIMESTAMP NOT NULL,
        PRIMARY KEY (\`id\`),
        KEY \`idx_transfer_history_receipt_created\` (\`transfer_receipt_id\`, \`created_at\`),
        KEY \`idx_transfer_history_actor\` (\`performed_by_account_id\`),
        CONSTRAINT \`fk_transfer_history_receipt\` FOREIGN KEY (\`transfer_receipt_id\`) REFERENCES \`transfer_receipts\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_transfer_history_actor\` FOREIGN KEY (\`performed_by_account_id\`) REFERENCES \`accounts\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE \`inventory_reservations\` (
        \`id\` BIGINT NOT NULL AUTO_INCREMENT,
        \`inventory_id\` BIGINT NOT NULL,
        \`order_item_id\` BIGINT NULL,
        \`transfer_receipt_item_id\` BIGINT NULL,
        \`quantity\` INTEGER NOT NULL,
        \`status\` ENUM('active', 'consumed', 'released', 'expired') NOT NULL DEFAULT 'active',
        \`expires_at\` TIMESTAMP NULL,
        \`confirmed_at\` TIMESTAMP NULL,
        \`consumed_at\` TIMESTAMP NULL,
        \`released_at\` TIMESTAMP NULL,
        \`idempotency_key\` VARCHAR(191) NOT NULL,
        \`created_at\` TIMESTAMP NOT NULL,
        \`updated_at\` TIMESTAMP NOT NULL,
        PRIMARY KEY (\`id\`),
        UNIQUE KEY \`uq_inventory_reservations_idempotency_key\` (\`idempotency_key\`),
        KEY \`idx_reservations_inventory_status\` (\`inventory_id\`, \`status\`),
        KEY \`idx_reservations_expiry\` (\`status\`, \`expires_at\`),
        KEY \`idx_reservations_order_item\` (\`order_item_id\`),
        KEY \`idx_reservations_transfer_item\` (\`transfer_receipt_item_id\`),
        CONSTRAINT \`chk_inventory_reservations_quantity\` CHECK (\`quantity\` > 0),
        CONSTRAINT \`chk_reservation_owner\` CHECK ((\`order_item_id\` IS NOT NULL AND \`transfer_receipt_item_id\` IS NULL) OR (\`order_item_id\` IS NULL AND \`transfer_receipt_item_id\` IS NOT NULL)),
        CONSTRAINT \`chk_reservation_consumed_time\` CHECK (\`status\` <> 'consumed' OR \`consumed_at\` IS NOT NULL),
        CONSTRAINT \`chk_reservation_released_time\` CHECK (\`status\` NOT IN ('released', 'expired') OR \`released_at\` IS NOT NULL),
        CONSTRAINT \`chk_confirmed_reservation_expiry\` CHECK (\`confirmed_at\` IS NULL OR \`expires_at\` IS NULL),
        CONSTRAINT \`fk_inventory_reservations_inventory\` FOREIGN KEY (\`inventory_id\`) REFERENCES \`inventories\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_inventory_reservations_order_item\` FOREIGN KEY (\`order_item_id\`) REFERENCES \`order_items\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_inventory_reservations_transfer_item\` FOREIGN KEY (\`transfer_receipt_item_id\`) REFERENCES \`transfer_receipt_items\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE \`inventory_movements\` (
        \`id\` BIGINT NOT NULL AUTO_INCREMENT,
        \`branch_id\` BIGINT NOT NULL,
        \`product_variant_id\` BIGINT NOT NULL,
        \`quantity_delta\` INTEGER NOT NULL,
        \`balance_after\` INTEGER NOT NULL,
        \`order_item_id\` BIGINT NULL,
        \`transfer_receipt_item_id\` BIGINT NULL,
        \`return_item_id\` BIGINT NULL,
        \`reason\` VARCHAR(100) NOT NULL,
        \`reference_type\` VARCHAR(100) NOT NULL,
        \`reference_id\` VARCHAR(100) NOT NULL,
        \`idempotency_key\` VARCHAR(191) NOT NULL,
        \`created_by_account_id\` BIGINT NULL,
        \`occurred_at\` TIMESTAMP NOT NULL,
        \`created_at\` TIMESTAMP NOT NULL,
        PRIMARY KEY (\`id\`),
        UNIQUE KEY \`uq_inventory_movements_idempotency_key\` (\`idempotency_key\`),
        KEY \`idx_inventory_movements_ledger\` (\`branch_id\`, \`product_variant_id\`, \`occurred_at\`),
        KEY \`idx_inventory_movements_variant\` (\`product_variant_id\`),
        KEY \`idx_inventory_movements_reference\` (\`reference_type\`, \`reference_id\`),
        KEY \`idx_inventory_movements_order_item\` (\`order_item_id\`),
        KEY \`idx_inventory_movements_transfer_item\` (\`transfer_receipt_item_id\`),
        KEY \`idx_inventory_movements_return_item\` (\`return_item_id\`),
        KEY \`idx_inventory_movements_actor\` (\`created_by_account_id\`),
        CONSTRAINT \`chk_inventory_movement_quantity\` CHECK (\`quantity_delta\` <> 0),
        CONSTRAINT \`chk_inventory_movement_balance\` CHECK (\`balance_after\` >= 0),
        CONSTRAINT \`chk_movement_single_source\` CHECK ((CASE WHEN \`order_item_id\` IS NULL THEN 0 ELSE 1 END) + (CASE WHEN \`transfer_receipt_item_id\` IS NULL THEN 0 ELSE 1 END) + (CASE WHEN \`return_item_id\` IS NULL THEN 0 ELSE 1 END) <= 1),
        CONSTRAINT \`fk_inventory_movements_branch\` FOREIGN KEY (\`branch_id\`) REFERENCES \`branches\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_inventory_movements_variant\` FOREIGN KEY (\`product_variant_id\`) REFERENCES \`product_variants\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_inventory_movements_actor\` FOREIGN KEY (\`created_by_account_id\`) REFERENCES \`accounts\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_inventory_movements_order_item\` FOREIGN KEY (\`order_item_id\`) REFERENCES \`order_items\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_inventory_movements_transfer_item\` FOREIGN KEY (\`transfer_receipt_item_id\`) REFERENCES \`transfer_receipt_items\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_inventory_movements_return_item\` FOREIGN KEY (\`return_item_id\`) REFERENCES \`return_items\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
];

const migration = {
    up: async (queryInterface: QueryInterface): Promise<void> => {
        const existingTables = new Set(
            (await queryInterface.showAllTables()).map((tableName) => tableName.toLowerCase()),
        );
        const overlappingTables = ownedTables.filter((tableName) => existingTables.has(tableName));
        if (overlappingTables.length > 0) {
            throw new Error(
                "Database V2 inventory baseline refuses to run when any owned table already exists: " +
                overlappingTables.join(", ") + ".",
            );
        }
        for (const statement of createStatements) {
            await queryInterface.sequelize.query(statement);
        }
    },
};

export default migration;
