import type { QueryInterface } from "sequelize";

const ownedTables = [
    "conversations",
    "messages",
    "conversation_events",
    "conversation_read_states",
    "assistant_runs",
    "notifications",
    "behavior_events",
    "customer_product_stats",
    "outbox_events",
] as const;

const createStatements = [
    `CREATE TABLE \`conversations\` (
        \`id\` BIGINT NOT NULL AUTO_INCREMENT,
        \`customer_id\` BIGINT NOT NULL,
        \`branch_id\` BIGINT NULL,
        \`assigned_account_id\` BIGINT NULL,
        \`subject\` VARCHAR(255) NULL,
        \`status\` ENUM('open', 'waiting_staff', 'closed') NOT NULL DEFAULT 'open',
        \`reply_mode\` ENUM('bot', 'human', 'paused') NOT NULL DEFAULT 'paused',
        \`version\` BIGINT NOT NULL DEFAULT 0,
        \`last_message_seq\` BIGINT NOT NULL DEFAULT 0,
        \`mode_changed_by_account_id\` BIGINT NULL,
        \`mode_changed_at\` TIMESTAMP NOT NULL,
        \`handoff_requested_at\` TIMESTAMP NULL,
        \`last_message_at\` TIMESTAMP NULL,
        \`closed_at\` TIMESTAMP NULL,
        \`created_at\` TIMESTAMP NOT NULL,
        \`updated_at\` TIMESTAMP NOT NULL,
        PRIMARY KEY (\`id\`),
        KEY \`idx_conversations_customer_created\` (\`customer_id\`, \`created_at\`),
        KEY \`idx_conversations_branch_queue\` (\`branch_id\`, \`status\`, \`last_message_at\`, \`id\`),
        KEY \`idx_conversations_assignee_queue\` (\`assigned_account_id\`, \`status\`, \`last_message_at\`, \`id\`),
        KEY \`idx_conversations_mode_actor\` (\`mode_changed_by_account_id\`),
        CONSTRAINT \`chk_conversation_version\` CHECK (\`version\` >= 0),
        CONSTRAINT \`chk_conversation_last_message_seq\` CHECK (\`last_message_seq\` >= 0),
        CONSTRAINT \`chk_conversation_human_owner\` CHECK (\`reply_mode\` <> 'human' OR (\`status\` = 'open' AND \`assigned_account_id\` IS NOT NULL)),
        CONSTRAINT \`chk_conversation_bot_owner\` CHECK (\`reply_mode\` <> 'bot' OR (\`status\` = 'open' AND \`assigned_account_id\` IS NULL)),
        CONSTRAINT \`chk_conversation_waiting_staff\` CHECK (\`status\` <> 'waiting_staff' OR (\`reply_mode\` = 'paused' AND \`assigned_account_id\` IS NULL AND \`handoff_requested_at\` IS NOT NULL)),
        CONSTRAINT \`chk_conversation_closed_state\` CHECK ((\`status\` = 'closed' AND \`reply_mode\` = 'paused' AND \`assigned_account_id\` IS NULL AND \`closed_at\` IS NOT NULL) OR (\`status\` <> 'closed' AND \`closed_at\` IS NULL)),
        CONSTRAINT \`chk_conversation_message_cursor\` CHECK ((\`last_message_seq\` = 0 AND \`last_message_at\` IS NULL) OR (\`last_message_seq\` > 0 AND \`last_message_at\` IS NOT NULL)),
        CONSTRAINT \`fk_conversations_customer\` FOREIGN KEY (\`customer_id\`) REFERENCES \`customers\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_conversations_branch\` FOREIGN KEY (\`branch_id\`) REFERENCES \`branches\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_conversations_assignee\` FOREIGN KEY (\`assigned_account_id\`) REFERENCES \`accounts\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_conversations_mode_actor\` FOREIGN KEY (\`mode_changed_by_account_id\`) REFERENCES \`accounts\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE \`messages\` (
        \`id\` BIGINT NOT NULL AUTO_INCREMENT,
        \`conversation_id\` BIGINT NOT NULL,
        \`seq\` BIGINT NOT NULL,
        \`sender_account_id\` BIGINT NULL,
        \`sender_type\` ENUM('customer', 'staff', 'assistant', 'system') NOT NULL,
        \`message_type\` ENUM('text', 'system_notice') NOT NULL DEFAULT 'text',
        \`dedup_key\` VARCHAR(191) NOT NULL,
        \`request_hash\` CHAR(64) NOT NULL,
        \`reply_to_message_id\` BIGINT NULL,
        \`content\` TEXT NOT NULL,
        \`metadata\` JSON NULL,
        \`created_at\` TIMESTAMP NOT NULL,
        PRIMARY KEY (\`id\`),
        CONSTRAINT \`uq_messages_conversation_seq\` UNIQUE (\`conversation_id\`, \`seq\`),
        CONSTRAINT \`uq_messages_conversation_dedup\` UNIQUE (\`conversation_id\`, \`dedup_key\`),
        KEY \`idx_messages_conversation_created\` (\`conversation_id\`, \`created_at\`),
        KEY \`idx_messages_sender\` (\`sender_account_id\`),
        KEY \`idx_messages_reply_to\` (\`reply_to_message_id\`),
        CONSTRAINT \`chk_message_seq\` CHECK (\`seq\` > 0),
        CONSTRAINT \`chk_message_sender_identity\` CHECK ((\`sender_type\` IN ('customer', 'staff') AND \`sender_account_id\` IS NOT NULL) OR (\`sender_type\` IN ('assistant', 'system') AND \`sender_account_id\` IS NULL)),
        CONSTRAINT \`chk_message_sender_content_type\` CHECK ((\`sender_type\` = 'system' AND \`message_type\` = 'system_notice') OR (\`sender_type\` <> 'system' AND \`message_type\` = 'text')),
        CONSTRAINT \`chk_message_nonempty_content\` CHECK (CHAR_LENGTH(TRIM(\`content\`)) > 0),
        CONSTRAINT \`fk_messages_conversation\` FOREIGN KEY (\`conversation_id\`) REFERENCES \`conversations\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_messages_sender\` FOREIGN KEY (\`sender_account_id\`) REFERENCES \`accounts\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_messages_reply_to\` FOREIGN KEY (\`reply_to_message_id\`) REFERENCES \`messages\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE \`conversation_events\` (
        \`id\` BIGINT NOT NULL AUTO_INCREMENT,
        \`conversation_id\` BIGINT NOT NULL,
        \`event_type\` ENUM('created', 'handoff_requested', 'claimed', 'assigned', 'routed', 'mode_changed', 'closed', 'reopened', 'assignee_released') NOT NULL,
        \`actor_account_id\` BIGINT NULL,
        \`from_mode\` ENUM('bot', 'human', 'paused') NULL,
        \`to_mode\` ENUM('bot', 'human', 'paused') NOT NULL,
        \`from_assignee_id\` BIGINT NULL,
        \`to_assignee_id\` BIGINT NULL,
        \`from_branch_id\` BIGINT NULL,
        \`to_branch_id\` BIGINT NULL,
        \`from_status\` ENUM('open', 'waiting_staff', 'closed') NULL,
        \`to_status\` ENUM('open', 'waiting_staff', 'closed') NOT NULL,
        \`version_after\` BIGINT NOT NULL,
        \`command_key\` VARCHAR(191) NOT NULL,
        \`request_hash\` CHAR(64) NOT NULL,
        \`reason_code\` VARCHAR(100) NULL,
        \`created_at\` TIMESTAMP NOT NULL,
        PRIMARY KEY (\`id\`),
        CONSTRAINT \`uq_conversation_events_command\` UNIQUE (\`conversation_id\`, \`command_key\`),
        CONSTRAINT \`uq_conversation_events_version\` UNIQUE (\`conversation_id\`, \`version_after\`),
        KEY \`idx_conversation_events_timeline\` (\`conversation_id\`, \`created_at\`, \`id\`),
        KEY \`idx_conversation_events_actor\` (\`actor_account_id\`),
        KEY \`idx_conversation_events_from_assignee\` (\`from_assignee_id\`),
        KEY \`idx_conversation_events_to_assignee\` (\`to_assignee_id\`),
        KEY \`idx_conversation_events_from_branch\` (\`from_branch_id\`),
        KEY \`idx_conversation_events_to_branch\` (\`to_branch_id\`),
        CONSTRAINT \`chk_conversation_event_version\` CHECK (\`version_after\` >= 0),
        CONSTRAINT \`chk_conversation_event_origin\` CHECK ((\`event_type\` = 'created' AND \`version_after\` = 0 AND \`from_mode\` IS NULL AND \`from_status\` IS NULL AND \`from_assignee_id\` IS NULL AND \`from_branch_id\` IS NULL) OR (\`event_type\` <> 'created' AND \`version_after\` > 0 AND \`from_mode\` IS NOT NULL AND \`from_status\` IS NOT NULL)),
        CONSTRAINT \`chk_conversation_event_human\` CHECK (\`to_mode\` <> 'human' OR (\`to_status\` = 'open' AND \`to_assignee_id\` IS NOT NULL)),
        CONSTRAINT \`chk_conversation_event_bot\` CHECK (\`to_mode\` <> 'bot' OR (\`to_status\` = 'open' AND \`to_assignee_id\` IS NULL)),
        CONSTRAINT \`chk_conversation_event_inactive\` CHECK (\`to_status\` = 'open' OR (\`to_mode\` = 'paused' AND \`to_assignee_id\` IS NULL)),
        CONSTRAINT \`fk_conversation_events_conversation\` FOREIGN KEY (\`conversation_id\`) REFERENCES \`conversations\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_conversation_events_actor\` FOREIGN KEY (\`actor_account_id\`) REFERENCES \`accounts\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_conversation_events_from_assignee\` FOREIGN KEY (\`from_assignee_id\`) REFERENCES \`accounts\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_conversation_events_to_assignee\` FOREIGN KEY (\`to_assignee_id\`) REFERENCES \`accounts\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_conversation_events_from_branch\` FOREIGN KEY (\`from_branch_id\`) REFERENCES \`branches\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_conversation_events_to_branch\` FOREIGN KEY (\`to_branch_id\`) REFERENCES \`branches\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE \`conversation_read_states\` (
        \`conversation_id\` BIGINT NOT NULL,
        \`account_id\` BIGINT NOT NULL,
        \`last_read_seq\` BIGINT NOT NULL DEFAULT 0,
        \`read_at\` TIMESTAMP NOT NULL,
        PRIMARY KEY (\`conversation_id\`, \`account_id\`),
        KEY \`idx_conversation_reads_account\` (\`account_id\`),
        CONSTRAINT \`chk_conversation_read_seq\` CHECK (\`last_read_seq\` >= 0),
        CONSTRAINT \`fk_conversation_reads_conversation\` FOREIGN KEY (\`conversation_id\`) REFERENCES \`conversations\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_conversation_reads_account\` FOREIGN KEY (\`account_id\`) REFERENCES \`accounts\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE \`assistant_runs\` (
        \`id\` BIGINT NOT NULL AUTO_INCREMENT,
        \`conversation_id\` BIGINT NOT NULL,
        \`trigger_message_id\` BIGINT NOT NULL,
        \`expected_version\` BIGINT NOT NULL,
        \`context_last_seq\` BIGINT NOT NULL,
        \`status\` ENUM('queued', 'generating', 'completed', 'failed', 'cancelled', 'superseded') NOT NULL DEFAULT 'queued',
        \`attempt_count\` INTEGER NOT NULL DEFAULT 0,
        \`next_attempt_at\` TIMESTAMP NULL,
        \`lease_token\` CHAR(36) NULL,
        \`lease_expires_at\` TIMESTAMP NULL,
        \`response_message_id\` BIGINT NULL,
        \`model_name\` VARCHAR(150) NULL,
        \`error_code\` VARCHAR(100) NULL,
        \`created_at\` TIMESTAMP NOT NULL,
        \`started_at\` TIMESTAMP NULL,
        \`completed_at\` TIMESTAMP NULL,
        PRIMARY KEY (\`id\`),
        CONSTRAINT \`uq_assistant_runs_trigger\` UNIQUE (\`conversation_id\`, \`trigger_message_id\`),
        UNIQUE KEY \`uq_assistant_runs_response\` (\`response_message_id\`),
        KEY \`idx_assistant_runs_ready\` (\`status\`, \`next_attempt_at\`, \`id\`),
        KEY \`idx_assistant_runs_lease\` (\`status\`, \`lease_expires_at\`, \`id\`),
        KEY \`idx_assistant_runs_conversation\` (\`conversation_id\`),
        CONSTRAINT \`chk_assistant_run_expected_version\` CHECK (\`expected_version\` >= 0),
        CONSTRAINT \`chk_assistant_run_context_seq\` CHECK (\`context_last_seq\` > 0),
        CONSTRAINT \`chk_assistant_run_attempts\` CHECK (\`attempt_count\` >= 0),
        CONSTRAINT \`chk_assistant_run_lease\` CHECK ((\`status\` = 'generating' AND \`lease_token\` IS NOT NULL AND \`lease_expires_at\` IS NOT NULL AND \`started_at\` IS NOT NULL AND \`attempt_count\` > 0) OR (\`status\` <> 'generating' AND \`lease_token\` IS NULL AND \`lease_expires_at\` IS NULL)),
        CONSTRAINT \`chk_assistant_run_schedule\` CHECK ((\`status\` = 'queued' AND \`next_attempt_at\` IS NOT NULL) OR (\`status\` <> 'queued' AND \`next_attempt_at\` IS NULL)),
        CONSTRAINT \`chk_assistant_run_terminal_time\` CHECK ((\`status\` IN ('completed', 'failed', 'cancelled', 'superseded') AND \`completed_at\` IS NOT NULL) OR (\`status\` IN ('queued', 'generating') AND \`completed_at\` IS NULL)),
        CONSTRAINT \`chk_assistant_run_response\` CHECK ((\`status\` = 'completed' AND \`response_message_id\` IS NOT NULL AND \`started_at\` IS NOT NULL AND \`attempt_count\` > 0) OR (\`status\` <> 'completed' AND \`response_message_id\` IS NULL)),
        CONSTRAINT \`fk_assistant_runs_conversation\` FOREIGN KEY (\`conversation_id\`) REFERENCES \`conversations\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_assistant_runs_trigger\` FOREIGN KEY (\`trigger_message_id\`) REFERENCES \`messages\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_assistant_runs_response\` FOREIGN KEY (\`response_message_id\`) REFERENCES \`messages\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE \`notifications\` (
        \`id\` BIGINT NOT NULL AUTO_INCREMENT,
        \`recipient_account_id\` BIGINT NOT NULL,
        \`type\` ENUM('order_new', 'order_updated', 'low_stock', 'stock_request', 'transfer_receipt', 'system') NOT NULL,
        \`title\` VARCHAR(255) NOT NULL,
        \`content\` VARCHAR(1000) NOT NULL,
        \`data\` JSON NULL,
        \`read_at\` TIMESTAMP NULL,
        \`created_at\` TIMESTAMP NOT NULL,
        PRIMARY KEY (\`id\`),
        KEY \`idx_notifications_recipient_read_created\` (\`recipient_account_id\`, \`read_at\`, \`created_at\`),
        CONSTRAINT \`fk_notifications_recipient\` FOREIGN KEY (\`recipient_account_id\`) REFERENCES \`accounts\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE \`behavior_events\` (
        \`id\` BIGINT NOT NULL AUTO_INCREMENT,
        \`customer_id\` BIGINT NULL,
        \`anonymous_session_id\` VARCHAR(100) NULL,
        \`product_id\` BIGINT NOT NULL,
        \`event_type\` ENUM('product_view', 'product_like', 'product_unlike', 'add_to_cart', 'purchase') NOT NULL,
        \`event_data\` JSON NULL,
        \`occurred_at\` TIMESTAMP NOT NULL,
        \`created_at\` TIMESTAMP NOT NULL,
        PRIMARY KEY (\`id\`),
        KEY \`idx_behavior_events_customer_occurred\` (\`customer_id\`, \`occurred_at\`),
        KEY \`idx_behavior_events_product_type_occurred\` (\`product_id\`, \`event_type\`, \`occurred_at\`),
        CONSTRAINT \`fk_behavior_events_customer\` FOREIGN KEY (\`customer_id\`) REFERENCES \`customers\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_behavior_events_product\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE \`customer_product_stats\` (
        \`id\` BIGINT NOT NULL AUTO_INCREMENT,
        \`customer_id\` BIGINT NOT NULL,
        \`product_id\` BIGINT NOT NULL,
        \`view_count\` INTEGER NOT NULL DEFAULT 0,
        \`is_liked\` BOOLEAN NOT NULL DEFAULT FALSE,
        \`last_viewed_at\` TIMESTAMP NULL,
        \`updated_at\` TIMESTAMP NOT NULL,
        PRIMARY KEY (\`id\`),
        CONSTRAINT \`uq_customer_product_stats_customer_product\` UNIQUE (\`customer_id\`, \`product_id\`),
        KEY \`idx_customer_product_stats_customer_updated\` (\`customer_id\`, \`updated_at\`),
        KEY \`idx_customer_product_stats_product\` (\`product_id\`),
        CONSTRAINT \`fk_customer_product_stats_customer\` FOREIGN KEY (\`customer_id\`) REFERENCES \`customers\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT \`fk_customer_product_stats_product\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
    `CREATE TABLE \`outbox_events\` (
        \`id\` BIGINT NOT NULL AUTO_INCREMENT,
        \`event_id\` CHAR(36) NOT NULL,
        \`event_type\` VARCHAR(100) NOT NULL,
        \`aggregate_type\` VARCHAR(100) NOT NULL,
        \`aggregate_id\` VARCHAR(100) NOT NULL,
        \`payload\` JSON NOT NULL,
        \`occurred_at\` TIMESTAMP NOT NULL,
        \`published_at\` TIMESTAMP NULL,
        \`attempts\` INTEGER NOT NULL DEFAULT 0,
        \`locked_at\` TIMESTAMP NULL,
        \`last_error\` TEXT NULL,
        \`created_at\` TIMESTAMP NOT NULL,
        \`updated_at\` TIMESTAMP NOT NULL,
        PRIMARY KEY (\`id\`),
        UNIQUE KEY \`uq_outbox_events_event_id\` (\`event_id\`),
        KEY \`idx_outbox_events_dispatch\` (\`published_at\`, \`locked_at\`, \`id\`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
];

const migration = {
    up: async (queryInterface: QueryInterface): Promise<void> => {
        const existingTables = new Set(
            (await queryInterface.showAllTables()).map((tableName) => tableName.toLowerCase()),
        );
        const overlappingTables = ownedTables.filter((tableName) => existingTables.has(tableName));
        if (overlappingTables.length > 0) {
            throw new Error(
                "Database V2 communication baseline refuses to run when any owned table already exists: " +
                overlappingTables.join(", ") + ".",
            );
        }
        for (const statement of createStatements) {
            await queryInterface.sequelize.query(statement);
        }
    },
};

export default migration;
