from typing import Protocol

from app.domain.models import Product, UserSignal


class ProductRepository(Protocol):
    async def list_products(self) -> list[Product]: ...

    async def get_user_signals(self, user_id: int) -> list[UserSignal]: ...


class ChatModel(Protocol):
    async def reply(self, message: str, products: list[Product]) -> dict[str, object]: ...


class EmbeddingModel(Protocol):
    async def embed_document(self, text: str) -> list[float]: ...

    async def embed_query(self, text: str) -> list[float]: ...


class ProductVectorStore(Protocol):
    async def ensure_collection(self) -> None: ...

    async def upsert(self, product: Product, vector: list[float]) -> None: ...

    async def delete(self, product_id: int) -> None: ...

    async def search(self, vector: list[float], limit: int) -> list[int]: ...
